development:
  access_key_id: AKIAICGCE5EYKOIYYZWQ
  secret_access_key: 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
  bucket: lifestylesz
  s3_region: us-west-2

test:
  access_key_id: AKIAICGCE5EYKOIYYZWQ
  secret_access_key: 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
  bucket: lifestylesz
  s3_protocol: http

production:
  access_key_id: AKIAICGCE5EYKOIYYZWQ
  secret_access_key: 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
  bucket: lifestylesz
  s3_protocol: https
  s3_region: us-west-2